FROM ubuntu:22.04

WORKDIR /home/workdir

# Install Python3.10
RUN apt update 
RUN apt upgrade -y
RUN apt install -y python3.10 

# For initial setting of Python
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1 
RUN apt install -y python3-pip 
RUN pip install -U pip 